### ISSUE TITLE
Using jitsu-hammer without a hardware sound card

### ISSUE THREAD

**Issue by ninioperdido** [jitsi/jitsi-hammer#2]
Hi Everybody!
Are there any configuration option in order to allow jitsi-hammer to run without a hardware sound card?

Using audiortpdump and videortpdump doesn't seems to help:

```
./jitsi-hammer.sh -audiortpdump ./ressources/rtp_opus.rtpdump -videortpdump ./ressources/rtp_vp8.rtpdump -users 5 -room TestHammer -MUCdomain conference.jitsi.mydomain.com -XMPPdomain jitsi.mydomain.com -XMPPhost jitsi.mydomain.com
...
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM dmix
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fda69b200f8, pid=3052, tid=140576567928576
#
# JRE version: OpenJDK Runtime Environment (7.0_65-b32) (build 1.7.0_65-b32)
# Java VM: OpenJDK 64-Bit Server VM (24.65-b04 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libjnportaudio.so+0xd0f8]  Pa_GetDeviceInfo+0x58
...
```

Thanks for all!

**Comment by dwilson6** [comment]
I can't seem to get the hammer running in a Docker container because of the lack of a sound device.  I've installed alsa-base and alsa-utils and started the alsa-utils service before running the hammer.

I see the same stacktrace as the first one in [ninioperdido's post above](https://github.com/jitsi/jitsi-hammer/issues/2#issuecomment-54671845). Any ideas?  How did you run your Docker container?
22:09:15.641 WARNING: [1] org.jitsi.impl.neomedia.device.DeviceSystem.warn() Failed to initialize org.jitsi.impl.neomedia.device.PulseAudioSystem
java.lang.IllegalStateException: context.state
